spring:
  profiles:
    group:
      local:
        - common
        - local_db
      test:
        - common
        - test_db

---

spring:
  config:
    activate:
      on-profile: common

server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true


---

spring:
  config:
    activate:
      on-profile: local_db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa_project?serverTimezone=Asia/Seoul
    username: study_user
    password: kdt_study
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        dialect:
        hbm2ddl:
          auto: none
